FROM public.ecr.aws/j4z6l8i6/amazon-textract-idp-cdk-construct-classification-spacy-lending-sample:latest

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "sync_main.lambda_handler" ]
